# Generated by Django 3.2.7 on 2022-05-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_id_brend_and_id_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='id_Brend_and_id_Category',
        ),
    ]
